Python script for database initialization with roles
Element84/swoop-db pull request #23
Opened 2023-07-24 14:22 UTC by geomatician

This Python script creates a new Database with roles for SWOOP API / Caboose / Conductor, and an owner role. 
The script is added to the Swoop-DB docker image at `quay.io/element84/swoop-db` via the Dockerfile. This PR is linked with [this other PR](https://github.com/Element84/filmdrop-k8s-tf-modules/pull/33) that creates a KubernetesJob in Terraform that runs this script.

2023-07-24 17:27 UTC, hectormachin requested changes

2023-07-24 17:27 UTC, hectormachin commented on bin/db-initialization.py
> +        dsn = "postgresql://postgres:password@postgres:5432/postgres"
Could we pass these credentials via ENV variables?

2023-07-24 17:27 UTC, hectormachin commented on Dockerfile
> +COPY bin/db-initialization.py home/db-initialization.py
Can we change the location of this script outside the home directory? Maybe somewhere within /opt/swoop/db?

2023-07-24 21:52 UTC, hectormachin approved these changes

2023-07-25 01:45 UTC, jkeifer requested changes
This is a good starting point, but I think it could use some refactoring and a few functional changes.

As an example of where I would take this, see https://github.com/Element84/swoop-db/pull/24/. Not that you have to use that example (but you can if you want).

2023-07-25 01:45 UTC, jkeifer commented on Dockerfile
> +    -o pgtap.tar.gz && \
This is a continuation of the previous line, not another command, so I don't think it should be unindented.

2023-07-25 01:45 UTC, jkeifer commented on bin/db-initialization.py
> +        conn = await asyncpg.connect(dsn=dsn)
See https://www.postgresql.org/docs/current/libpq-envars.html. We should be using these environment variables alone to define the connection parameters. By leaving the connection parameters to environment variables in this way we automatically support all connection parameters supported by libpq _without code changes_.

These lines can then simply become:

```suggestion
        conn = await asyncpg.connect(database="")
```

Note that the definition of `database` here overrides anything set in the `PGDATABASE` env var, so we can use that var for the name of the database we want to create, which means we don't have to specify a "special" var (`DATABASE_TO_CREATE`) for this script.

2023-07-25 01:45 UTC, jkeifer commented on bin/db-initialization.py
> +                CREATE ROLE :un WITH CREATEDB CREATEROLE LOGIN PASSWORD ':pw';
This user should not have `CREATEDB` or `CREATEROLE` permissions.

2023-07-25 01:45 UTC, jkeifer commented on bin/db-initialization.py
> +        # Create database with owner role as owner
All of this is the same code, it can be collapsed into a loop.

2023-07-25 01:45 UTC, jkeifer commented on bin/db-initialization.py
> +                CREATE ROLE :un WITH LOGIN IN ROLE :ir PASSWORD ':pw';
Idempotency is important; how do you ensure this script can run again without errors?

To expand upon this, if something goes wrong while running this script a first time, we want to be able to run it again and have it pick up where it left off, not error out when it was only partially applied.

2023-07-25 01:45 UTC, jkeifer commented on bin/db-initialization.py
> +DB_NAME = os.environ["DATABASE_TO_CREATE"]
Generally speaking, you should avoid reading env vars as part of module initialization. It makes it difficult if you want to override them after importing.

2023-07-25 01:45 UTC, jkeifer commented on bin/db-initialization.py
> +from buildpg import V, asyncpg, render
You aren't using the special `buildpg` extensions to `asyncpg`, so it seems like this should be a vanilla `asyncpg` import.

2023-07-25 01:45 UTC, jkeifer commented on bin/db-initialization.py
> +def db_initialization():
Seems like this should be the async function, and just wrap the call in the main check instead of in this function.

2023-07-25 01:45 UTC, jkeifer commented on bin/db-initialization.py
> +def db_initialization():
Also, this function is really long. It doesn't do a whole lot, but it doesn't look like it. I think breaking it down in to smaller, self-documenting functions would make the code more obvious.

2023-07-25 01:45 UTC, jkeifer commented on bin/db-initialization.py
> +import asyncio
It's a good idea to make scripts executable and add a shebang so they can be run directly.

It also seems like we need some documentation in this script explaining how to run it.

2023-07-25 17:48 UTC, hectormachin commented on Dockerfile
> +    -o pgtap.tar.gz && \
resolved

2023-07-25 17:48 UTC, hectormachin approved these changes

2023-07-25 17:48 UTC, merged